$$ \huge{\text{One-Hot Titanic}}$$


# Logistic Regression  For Titanic data set

<font size=4 >   See [here](https://towardsdatascience.com/a-beginners-guide-to-kaggle-s-titanic-problem-3193cb56f6ca) for more on the Titanic data set. We are interested in predicting if a passenger survived.
    

In [2]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/lammersm/Data/main/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

<font size=4 color=blue > There are a lot of NANs (missing values) for this data set.  Let's count them by feature.

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

<font size=4 color=blue> Find the correlation matrix.  Notice that correlation only does the numeric values. 

In [4]:
df.corr()

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'

<font  size=4> Let's peel off some of the features in a new data frame and drop the Nans.  

In [5]:
df_sub=df[["Survived","Fare",'Sex', "Pclass","Embarked"]]
print(df_sub.shape)
df_sub=df_sub.dropna()
print(df_sub.shape)

(891, 5)
(889, 5)


<font size=4 color=blue> Separate the categorical, the numeric and the target.( I did all the analysis with data frames and did not have to switch to np arrays)  

In [6]:
df_num=(df_sub[["Fare"]])
df_cat=(df_sub[['Sex', "Pclass","Embarked"]])
df_surv=df_sub["Survived"] 

<font size=4 color=blue > Logistic regression requires numeric values so create a model using only fare.  use parameter 
    
    C=10 and random_state=42

In [7]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression( C=10,random_state=42)# The C value 
log_reg.fit(df_num, df_surv)

LogisticRegression(C=10, random_state=42)

<font size=4  color =blue> Do a 5 fold CV and print the average of the scores.

In [9]:
from sklearn.model_selection import cross_val_score
import numpy as np
cvs=cross_val_score(log_reg, df_num, df_surv, cv=5
                    , scoring='accuracy')
print(cvs)
print("Average of the scores",np.mean(cvs))

[0.58988764 0.70786517 0.66853933 0.67977528 0.66666667]
Average of the scores 0.6625468164794006


# Using  Categorical data as a feature for classification.

<font size=4 color =blue> Apply a one hot encoder to categorical data. Compare original categorical with and one-hot encoded data.

In [10]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(drop='if_binary',sparse_output=False).set_output(transform="pandas")
hot_str=enc.fit_transform(df_cat)

In [11]:
df_cat

Sex  Pclass Embarked
0      male       3        S
1    female       1        C
2    female       3        S
3    female       1        S
4      male       3        S
..      ...     ...      ...
886    male       2        S
887  female       1        S
888  female       3        S
889    male       1        C
890    male       3        Q

[889 rows x 3 columns]

In [12]:
hot_str

Sex_male  Pclass_1  Pclass_2  Pclass_3  Embarked_C  Embarked_Q  \
0         1.0       0.0       0.0       1.0         0.0         0.0   
1         0.0       1.0       0.0       0.0         1.0         0.0   
2         0.0       0.0       0.0       1.0         0.0         0.0   
3         0.0       1.0       0.0       0.0         0.0         0.0   
4         1.0       0.0       0.0       1.0         0.0         0.0   
..        ...       ...       ...       ...         ...         ...   
886       1.0       0.0       1.0       0.0         0.0         0.0   
887       0.0       1.0       0.0       0.0         0.0         0.0   
888       0.0       0.0       0.0       1.0         0.0         0.0   
889       1.0       1.0       0.0       0.0         1.0         0.0   
890       1.0       0.0       0.0       1.0         0.0         1.0   

     Embarked_S  
0           1.0  
1           0.0  
2           1.0  
3           1.0  
4           1.0  
..          ...  
886         1.0  
887         1.0  
888         1.0  
889         0.0  
890         0.0  

[889 rows x 7 columns]

<font size=4 color =blue> Join the encoded data with the target and the numeric data and look at the correlations.  Do you notice anything about correlations with the encoded variables and Survived?  Does this make sense?  

In [13]:
df_all=df_num.join(hot_str).join(df_surv)
df_all.corr()

Fare  Sex_male  Pclass_1  Pclass_2  Pclass_3  Embarked_C  \
Fare        1.000000 -0.179958  0.590576 -0.117609 -0.411932    0.270731   
Sex_male   -0.179958  1.000000 -0.093142 -0.066459  0.134227   -0.084520   
Pclass_1    0.590576 -0.093142  1.000000 -0.287653 -0.625395    0.299472   
Pclass_2   -0.117609 -0.066459 -0.287653  1.000000 -0.567432   -0.126039   
Pclass_3   -0.411932  0.134227 -0.625395 -0.567432  1.000000   -0.154785   
Embarked_C  0.270731 -0.084520  0.299472 -0.126039 -0.154785    1.000000   
Embarked_Q -0.116684 -0.075217 -0.154680 -0.127705  0.237035   -0.148646   
Embarked_S -0.163758  0.121405 -0.165022  0.190824 -0.013594   -0.782613   
Survived    0.255290 -0.541585  0.282368  0.095002 -0.320171    0.169966   

            Embarked_Q  Embarked_S  Survived  
Fare         -0.116684   -0.163758  0.255290  
Sex_male     -0.075217    0.121405 -0.541585  
Pclass_1     -0.154680   -0.165022  0.282368  
Pclass_2     -0.127705    0.190824  0.095002  
Pclass_3      0.237035   -0.013594 -0.320171  
Embarked_C   -0.148646   -0.782613  0.169966  
Embarked_Q    1.000000   -0.499261  0.004536  
Embarked_S   -0.499261    1.000000 -0.151777  
Survived      0.004536   -0.151777  1.000000

<font size=4, color =brown> __Answer__

In [14]:
df_feat=df_num.join(hot_str)

<font size =4 color=blue> Now try a Logistic Regressor  using all the data. Use a 5 fold CV like above and compare the results to those above.  Scale the data first. ( you do not need to train test split)

In [15]:
#from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
X_finalS=SS.fit_transform(df_feat)
#X_finalS

In [16]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression( C=10,random_state=42)# The C value 
log_reg.fit(X_finalS, df_surv)

LogisticRegression(C=10, random_state=42)

In [17]:
from sklearn.model_selection import cross_val_score
cvs=cross_val_score(log_reg, X_finalS, df_surv, cv=5
                    , scoring='accuracy')
print(cvs)
print("Average of the scores",np.mean(cvs))

[0.75842697 0.79213483 0.78089888 0.75842697 0.78531073]
Average of the scores 0.775039674982543


 <font size=4 color=blue>  What features are most highly correlated with survival? Does this make sense?
    

In [18]:
log_reg.coef_

array([[ 0.06101206, -1.23822349,  0.38512295,  0.12025571, -0.42909036,
         0.1135347 ,  0.04645906, -0.1287236 ]])

<font color=brown> __Answer__